"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['ftdx1200_eq.py']
DATA_FILES = []
OPTIONS = {'includes':['tkinter', 'serial', 'sys', 'glob', 'time']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
